<?php

// connectinon of db
include_once('db_connect.php');
//db connected

//ob_start() is a function in PHP that is used to turn on output buffering. 
// Output buffering is a mechanism that allows you to capture the output generated by PHP, instead of sending it directly to the browser.
ob_start();

session_start(); // is a PHP function used to initiate a new or resume an existing session.

//checking if username and password is set or not
if(!isset($_POST['username']))
{
    header('location:login.php');
}
if(!isset($_POST['pass']))
{
    header('location:login.php');
}

$user=$_POST['username'];
$pass=$_POST['pass'];
$user_type=$_POST['User_type'];
$str_pass=password_hash($pass,PASSWORD_BCRYPT);
$email=$_POST['email'];
$contact=$_POST['contact'];
//checking 

if($user_type=="User"){
    $query="SELECT * FROM `user` WHERE username= '$user'";
    $result= mysqli_query($con,$query);
    $num = mysqli_num_rows($result);
    if($num>=1){
        // This is a JavaScript function call. It opens a new browser window or tab with the URL 'signup.php'. 
        // The second argument _self specifies that the URL should be loaded in the same window or tab.
        echo "<script>alert('username already exist, choose a diffrent username')</script>";
        echo "<script>window.open('signup.php','_self')</script>";
        }
        else{
            $insert = "INSERT INTO `user`(`username`, `pass`, `email`, `contact no`) VALUES ('$user','$str_pass','$email','$contact')";
            if($insert=mysqli_query($con,$insert)){
                $register="successfully registered now login";
                $_SESSION['insert']=$register; 
                header('location:login.php');
            }
        }
}
else{
    $query="SELECT * FROM `restaurant` WHERE username= '$user'";
    $result= mysqli_query($con,$query);
    $num = mysqli_num_rows($result);
    if($num>=1){
        // This is a JavaScript function call. It opens a new browser window or tab with the URL 'signup.php'. 
        // The second argument _self specifies that the URL should be loaded in the same window or tab.
        echo "<script>alert('username already exist, choose a diffrent username')</script>";
        echo "<script>window.open('signup.php','_self')</script>";
        }
        else{
            $insert = "INSERT INTO `Restaurant`(`username`, `pass`, `email`, `contact no`) VALUES ('$user','$pass','$email','$contact')";
            if($insert=mysqli_query($con,$insert)){
                $register="successfully registered now login";
                $_SESSION['insert']=$register; 
                //http response made
                header('location:login.php');
            }
        }
}





?>